// npm i @mui/icons-material
// npm install @mui/material @emotion/react @emotion/styled for stylign
// npm i react-redux @reduxjs/toolkit
// npm install @mui/x-data-grid for data-grid-tables
import type { Metadata } from "next";
import "./globals.css";
import { MaterialRTLProvider } from "./MaterialUiRTL";
import localFont from "next/font/local";
import CustomThemeProvider from "./MaterialUiThemeProvider";
import { ReduxProvider } from "./GlobalRedux/provider";

// const inter = Inter({ subsets: ["latin"] });

// this is the way of importing a local font
const IranSansWeb = localFont({
  src: "../public/fonts/teqh_iransansweb.ttf",
  variable: "--font-IranSansWeb",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" dir="rtl">
      <head>
        <link rel="icon" href="/trade-logo-brad.png" />
      </head>
      {/* this MaterialRTLProvider is a context that provides the functionality of right to left   */}
      <MaterialRTLProvider>
        <body className={IranSansWeb.variable}>
          {/* this Providers is a provider of redux-toolkit */}
          <ReduxProvider>
            {/* this CustomThemeProvider is a provider of material ui for the app theme */}
            <CustomThemeProvider>{children}</CustomThemeProvider>
          </ReduxProvider>
        </body>
      </MaterialRTLProvider>
    </html>
  );
}
