// npm i @mui/icons-material
// npm install @mui/material @emotion/react @emotion/styled for stylign

import type { Metadata } from "next";
import "./globals.css";
import { MaterialRTLProvider } from "./MaterialUiRTL";
import localFont from "next/font/local";
import CustomThemeProvider from "./MaterialUiThemeProvider";

// const inter = Inter({ subsets: ["latin"] });

// this is the way of importing a local font
const IranSansWeb = localFont({
  src: "../public/fonts/teqh_iransansweb.ttf",
  variable: "--font-IranSansWeb",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" dir="rtl">
      <head>
        <link rel="icon" href="/trade-logo-brad.png" />
      </head>
      <CustomThemeProvider>
        {/* this MaterialRTLProvider is a context that provides the functionality of right to left   */}
        <MaterialRTLProvider>
          <body className={IranSansWeb.variable}>{children}</body>
        </MaterialRTLProvider>
      </CustomThemeProvider>
    </html>
  );
}
